# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sfdevtools.grpc_protos.peacock_pb2 as peacock__pb2


class PeacockStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveFileToColud = channel.unary_unary(
                '/peacock.Peacock/SaveFileToColud',
                request_serializer=peacock__pb2.SaveFileToColud_Msg.SerializeToString,
                response_deserializer=peacock__pb2.NoneReply.FromString,
                )
        self.SaveRefDataFromQC = channel.unary_unary(
                '/peacock.Peacock/SaveRefDataFromQC',
                request_serializer=peacock__pb2.SaveRefDataFromQC_Msg.SerializeToString,
                response_deserializer=peacock__pb2.NoneReply.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/peacock.Peacock/HealthCheck',
                request_serializer=peacock__pb2.Ping.SerializeToString,
                response_deserializer=peacock__pb2.Pong.FromString,
                )


class PeacockServicer(object):
    """The greeting service definition.
    """

    def SaveFileToColud(self, request, context):
        """Unary - request and respond
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveRefDataFromQC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeacockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveFileToColud': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFileToColud,
                    request_deserializer=peacock__pb2.SaveFileToColud_Msg.FromString,
                    response_serializer=peacock__pb2.NoneReply.SerializeToString,
            ),
            'SaveRefDataFromQC': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveRefDataFromQC,
                    request_deserializer=peacock__pb2.SaveRefDataFromQC_Msg.FromString,
                    response_serializer=peacock__pb2.NoneReply.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=peacock__pb2.Ping.FromString,
                    response_serializer=peacock__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peacock.Peacock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Peacock(object):
    """The greeting service definition.
    """

    @staticmethod
    def SaveFileToColud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peacock.Peacock/SaveFileToColud',
            peacock__pb2.SaveFileToColud_Msg.SerializeToString,
            peacock__pb2.NoneReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveRefDataFromQC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peacock.Peacock/SaveRefDataFromQC',
            peacock__pb2.SaveRefDataFromQC_Msg.SerializeToString,
            peacock__pb2.NoneReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peacock.Peacock/HealthCheck',
            peacock__pb2.Ping.SerializeToString,
            peacock__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
