# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sfdevtools.grpc_protos.python_showcases_pb2 as python__showcases__pb2


class Python_showcasesStub(object):
    """The python_showcases service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/python_showcases.Python_showcases/HealthCheck',
                request_serializer=python__showcases__pb2.Ping.SerializeToString,
                response_deserializer=python__showcases__pb2.Pong.FromString,
                )


class Python_showcasesServicer(object):
    """The python_showcases service definition.
    """

    def HealthCheck(self, request, context):
        """Unary - request and respond
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Python_showcasesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=python__showcases__pb2.Ping.FromString,
                    response_serializer=python__showcases__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'python_showcases.Python_showcases', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Python_showcases(object):
    """The python_showcases service definition.
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/python_showcases.Python_showcases/HealthCheck',
            python__showcases__pb2.Ping.SerializeToString,
            python__showcases__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
