steps:
- id: "Build Image using Pack"
  name: 'gcr.io/k8s-skaffold/pack:latest'
  entrypoint: "pack"
  dir: 'lab-8-build-and-deploy-cloud-run-service-using-buildconfig-and-buildpacks/microservices/customers'
  args: ['build', 
          '--builder', 'gcr.io/buildpacks/builder', 
          '--publish', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-monkey-artifact-registry/lab-08-get-customers-svc-img']

- id: "Deploy Cloud Run Service"
  name: 'gcr.io/cloud-builders/gcloud:latest'
  args: [
    'run', 'deploy', 'lab-08-get-customers-svc', 
    '--service-account' ,'sa-customers-svc@${PROJECT_ID}.iam.gserviceaccount.com',
    '--allow-unauthenticated',
    '--memory', '256Mi',
    '--platform', 'managed',
    '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-monkey-artifact-registry/lab-08-get-customers-svc-img',
    '--timeout', '30',
    '--min-instances', '0',
    '--max-instances', '1',
    '--ingress', 'all',
    '--region', 'us-central1',
    ]

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  