" turn relative line numbers on
:set relativenumber
:set rnu

" highlight current line
: set cursorline
" highlight current column
" : set cursorcolumn
" highlight search
: set hlsearch

: colorscheme desert
