
# FROM ubuntu:16.04 AS builder
# FROM ubuntu:18.04 AS builder
# FROM ubuntu:20.04 AS builder
FROM ubuntu:22.04 AS builder
# FROM gcc:7.2.0 As builder

## for gcc specific version only --- install packages from repository
# learn from: https://unix.stackexchange.com/a/743843/56400
# there are 3 outdated sources in the file, we need to change it to the archive database so that we can install packages
#### $ cat /etc/apt/sources.list
#### deb http://deb.debian.org/debian stretch main
#### deb http://deb.debian.org/debian stretch-updates main
#### deb http://security.debian.org stretch/updates main

# RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
## for gcc specific version only --- end

RUN apt-get update
RUN apt-get -y install vim

WORKDIR /SoftwareDev_Docker/

# fix bug https://github.com/Netflix/security_monkey/issues/1197 --- hunged during Geographic area
ARG DEBIAN_FRONTEND=noninteractive


# autoconf used by libpqxx
RUN apt-get update && apt-get -y install build-essential vim ninja-build doxygen git gitk wget \
    gdb curl zip pkg-config doxygen graphviz meld \
    cscope global autoconf cmake lcov \
    libx11-dev libxpm-dev libxaw7-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgnutls.*-dev libtinfo*

FROM builder AS round1
# build emacs in image
RUN wget https://ftp.gnu.org/gnu/emacs/emacs-29.1.tar.xz && tar xvf emacs-29.1.tar.xz && cd ./emacs-29.1 && ./configure && make && make install

# create user to avoid using root
ARG DOCKER_GID
ARG DOCKER_UID
ARG DOCKER_GNAME
ARG DOCKER_UNAME

# Create a group and user
RUN [ $DOCKER_UNAME = "root" ] && echo "No need to create root again" || ( groupadd -g $DOCKER_GID $DOCKER_GNAME || true && useradd -rm -d /home/$DOCKER_UNAME -s /bin/bash -g $DOCKER_GNAME -G sudo -u $DOCKER_UID $DOCKER_UNAME)

FROM round1 AS round2
## for the second round
COPY additional_scripts/ .
RUN cp -rf .spacemacs .spacemacs.env .emacs.d /home/$DOCKER_UNAME
RUN chown -R $DOCKER_UNAME:$DOCKER_UNAME /home/$DOCKER_UNAME/.spacemacs /home/$DOCKER_UNAME/.spacemacs.env /home/$DOCKER_UNAME/.emacs.d
