-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS hk.company
(
    id text NOT NULL,
    name text NOT NULL,
    start_up_time timestamp with time zone,
    owner text[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hk.employee
(
    id text NOT NULL,
    name text NOT NULL,
    gender text,
    is_full_time boolean,
    join_time timestamp with time zone,
    department_id text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hk.department
(
    id text NOT NULL,
    name text NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    address text,
    company_id text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS hk.employee
    ADD FOREIGN KEY (department_id)
    REFERENCES hk.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hk.department
    ADD FOREIGN KEY (company_id)
    REFERENCES hk.company (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
