
apiVersion: apps/v1
kind: Deployment
metadata:
  name: german-learning-tools
spec:
  selector:
    matchLabels:
      app: german-learning-tools
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: german-learning-tools
    spec:
      containers:
      - name: german-learning-tools
        # Note to deployer - add -dev at the end of here for development version
        # https://juju.is/tutorials/using-gitlab-as-a-container-registry#7-pull-your-container
        # https://stackoverflow.com/questions/49669077/helm-chart-deployment-and-private-docker-repository
        # https://medium.com/devops-with-valentine/gitlab-ci-how-to-pull-a-private-docker-image-from-aws-ecr-in-your-pipeline-515285569231
        image: {{ .Values.ImageNameTag }}
{{- if .Values.service.customProbe }}
{{ toYaml .Values.service.customProbe | indent 8 }}
{{- end }}
        env:
{{ toYaml .Values.service.env | indent 10 }}
      imagePullSecrets:
      - name: german-learning-tools-regcred
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: german-learning-tools
#   namespace: default
# spec:
#   maxReplicas: 2
#   minReplicas: 1
#   scaleTargetRef:
#     apiVersion: extensions/v1beta1
#     kind: Deployment
#     name: german-learning-tools
#   targetCPUUtilizationPercentage: 400
---
apiVersion: v1
kind: Service
metadata:
  name: srv-german-learning-tools

spec:
  selector:
    app: german-learning-tools

  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  type: {{ .Values.service.type }}