
ImageNameTag: public_ip_reporter:runner_1.0.0_sulfredm
# ImageNameTag: registry.gitlab.com/<gitlab group path>/public_ip_reporter:runner_1.0.0

service:
  # {}
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - name: website
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: grpc-api
      port: 50051
      protocol: TCP
      targetPort: 50051
  env:
    - name: FLASK_APP
      value: "app"
    - name: FLASK_DEBUG
      value: "True"
    - name: FLASK_RUN_HOST
      value: "0.0.0.0"
    - name: FLASK_RUN_PORT
      value: "5000"
    - name: GRPC_RUN_HOST
      value: "0.0.0.0"
    - name: GRPC_RUN_PORT
      value: "50051"
  customProbe:
    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 10
      httpGet:
        path: /healthcheck
        port: 5000
      # Example for grpc server
      # exec:
      #   command:
      #     - /bin/bash
      #     - -c
      #     - bash public_ip_reporter/app/grpc_api/healthcheck.sh
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 10
      httpGet:
        path: /healthcheck
        port: 5000
      # Example for grpc server
      # exec:
      #   command:
      #     - /bin/bash
      #     - -c
      #     - bash public_ip_reporter/app/grpc_api/healthcheck.sh